autoInstallPeers: false

catalog:
  vitest: ^4.1.9

color: always

gitChecks: false

minimumReleaseAgeExclude:
  - '@prettier/*'
  - '@vitest/*'
  - prettier
  - vitest

overrides:
  vite-plus>oxfmt: '-'
  vite-plus>vitest: 'catalog:'

peerDependencyRules:
  allowAny:
    - '@vitest/coverage-v8'
    - vitest

strictPeerDependencies: true

trustPolicy: no-downgrade
