autoInstallPeers: false

color: always

gitChecks: false

minimumReleaseAgeExclude:
  - '@prettier/*'
  - '@standard-config/*'
  - '@vitest/*'
  - prettier
  - vitest

overrides:
  vite-plus>@vitest/browser: '-'
  vite-plus>@vitest/browser-preview: '-'
  vite-plus>@vitest/expect: '-'
  vite-plus>@vitest/mocker: '-'
  vite-plus>@vitest/pretty-format: '-'
  vite-plus>@vitest/runner: '-'
  vite-plus>@vitest/snapshot: '-'
  vite-plus>@vitest/spy: '-'
  vite-plus>@vitest/utils: '-'
  vite-plus>oxfmt: '-'
  vite-plus>oxlint: latest
  vite-plus>oxlint-tsgolint: latest
  vite-plus>vitest: '-'

peerDependencyRules:
  allowAny:
    - '@vitest/coverage-v8'
    - vitest

strictPeerDependencies: true

trustPolicy: no-downgrade
