name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    name: node@${{ matrix.node-version }} / vitest@${{ matrix.vitest-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 20
          - 22
          - 24
          - latest
        vitest-version:
          - 4
          - 5
        exclude:
          - node-version: 20
            vitest-version: 5
    steps:
      - uses: actions/checkout@v7.0.0
        with:
          persist-credentials: false
      - uses: actions/setup-node@v6.4.0
        with:
          node-version: ${{ matrix.node-version }}
      - run: node --version
      - uses: pnpm/action-setup@v6.0.9
        with:
          cache: true
      - run: pnpm install
      - run: pnpm add --save-dev vite vitest@beta
        if: ${{ matrix.vitest-version == '5' }}
      - run: pnpm exec vitest --version
      - run: pnpm test
